/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package srcl_lcm_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class Graph_t implements lcm.lcm.LCMEncodable
{
    public long edge_num;
    public long vertex_num;
    public srcl_lcm_msgs.Vertex_t vertices[];
    public srcl_lcm_msgs.Edge_t edges[];
 
    public Graph_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xd1b7a0c2dd255080L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(srcl_lcm_msgs.Graph_t.class))
            return 0L;
 
        classes.add(srcl_lcm_msgs.Graph_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + srcl_lcm_msgs.Vertex_t._hashRecursive(classes)
             + srcl_lcm_msgs.Edge_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.edge_num); 
 
        outs.writeLong(this.vertex_num); 
 
        for (int a = 0; a < this.vertex_num; a++) {
            this.vertices[a]._encodeRecursive(outs); 
        }
 
        for (int a = 0; a < this.edge_num; a++) {
            this.edges[a]._encodeRecursive(outs); 
        }
 
    }
 
    public Graph_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public Graph_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static srcl_lcm_msgs.Graph_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        srcl_lcm_msgs.Graph_t o = new srcl_lcm_msgs.Graph_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.edge_num = ins.readLong();
 
        this.vertex_num = ins.readLong();
 
        this.vertices = new srcl_lcm_msgs.Vertex_t[(int) vertex_num];
        for (int a = 0; a < this.vertex_num; a++) {
            this.vertices[a] = srcl_lcm_msgs.Vertex_t._decodeRecursiveFactory(ins);
        }
 
        this.edges = new srcl_lcm_msgs.Edge_t[(int) edge_num];
        for (int a = 0; a < this.edge_num; a++) {
            this.edges[a] = srcl_lcm_msgs.Edge_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public srcl_lcm_msgs.Graph_t copy()
    {
        srcl_lcm_msgs.Graph_t outobj = new srcl_lcm_msgs.Graph_t();
        outobj.edge_num = this.edge_num;
 
        outobj.vertex_num = this.vertex_num;
 
        outobj.vertices = new srcl_lcm_msgs.Vertex_t[(int) vertex_num];
        for (int a = 0; a < this.vertex_num; a++) {
            outobj.vertices[a] = this.vertices[a].copy();
        }
 
        outobj.edges = new srcl_lcm_msgs.Edge_t[(int) edge_num];
        for (int a = 0; a < this.edge_num; a++) {
            outobj.edges[a] = this.edges[a].copy();
        }
 
        return outobj;
    }
 
}

