/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package srcl_lcm_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class TimeStamp_t implements lcm.lcm.LCMEncodable
{
    public long time_stamp;
 
    public TimeStamp_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x7cdccc00def406c5L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(srcl_lcm_msgs.TimeStamp_t.class))
            return 0L;
 
        classes.add(srcl_lcm_msgs.TimeStamp_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.time_stamp); 
 
    }
 
    public TimeStamp_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public TimeStamp_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static srcl_lcm_msgs.TimeStamp_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        srcl_lcm_msgs.TimeStamp_t o = new srcl_lcm_msgs.TimeStamp_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.time_stamp = ins.readLong();
 
    }
 
    public srcl_lcm_msgs.TimeStamp_t copy()
    {
        srcl_lcm_msgs.TimeStamp_t outobj = new srcl_lcm_msgs.TimeStamp_t();
        outobj.time_stamp = this.time_stamp;
 
        return outobj;
    }
 
}

