/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package srcl_lcm_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class WayPoint_t implements lcm.lcm.LCMEncodable
{
    public float positions[];
    public float yaw;
 
    public WayPoint_t()
    {
        positions = new float[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x21fd4a26a077af97L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(srcl_lcm_msgs.WayPoint_t.class))
            return 0L;
 
        classes.add(srcl_lcm_msgs.WayPoint_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.positions[a]); 
        }
 
        outs.writeFloat(this.yaw); 
 
    }
 
    public WayPoint_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public WayPoint_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static srcl_lcm_msgs.WayPoint_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        srcl_lcm_msgs.WayPoint_t o = new srcl_lcm_msgs.WayPoint_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.positions = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.positions[a] = ins.readFloat();
        }
 
        this.yaw = ins.readFloat();
 
    }
 
    public srcl_lcm_msgs.WayPoint_t copy()
    {
        srcl_lcm_msgs.WayPoint_t outobj = new srcl_lcm_msgs.WayPoint_t();
        outobj.positions = new float[(int) 3];
        System.arraycopy(this.positions, 0, outobj.positions, 0, 3); 
        outobj.yaw = this.yaw;
 
        return outobj;
    }
 
}

