"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class CarCommand_t(object):
    __slots__ = ["update_servo", "update_motor", "servo", "motor"]

    __typenames__ = ["boolean", "boolean", "float", "float"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.update_servo = False
        self.update_motor = False
        self.servo = 0.0
        self.motor = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(CarCommand_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bbff", self.update_servo, self.update_motor, self.servo, self.motor))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != CarCommand_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return CarCommand_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = CarCommand_t()
        self.update_servo = bool(struct.unpack('b', buf.read(1))[0])
        self.update_motor = bool(struct.unpack('b', buf.read(1))[0])
        self.servo, self.motor = struct.unpack(">ff", buf.read(8))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if CarCommand_t in parents: return 0
        tmphash = (0x795d25c3afe20100) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if CarCommand_t._packed_fingerprint is None:
            CarCommand_t._packed_fingerprint = struct.pack(">Q", CarCommand_t._get_hash_recursive([]))
        return CarCommand_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

