"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import librav_lcm_msgs.Vector2

class CarPose_t(object):
    __slots__ = ["mtime", "position", "theta"]

    __typenames__ = ["int64_t", "librav_lcm_msgs.Vector2", "double"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.mtime = 0
        self.position = librav_lcm_msgs.Vector2()
        self.theta = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(CarPose_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.mtime))
        assert self.position._get_packed_fingerprint() == librav_lcm_msgs.Vector2._get_packed_fingerprint()
        self.position._encode_one(buf)
        buf.write(struct.pack(">d", self.theta))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != CarPose_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return CarPose_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = CarPose_t()
        self.mtime = struct.unpack(">q", buf.read(8))[0]
        self.position = librav_lcm_msgs.Vector2._decode_one(buf)
        self.theta = struct.unpack(">d", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if CarPose_t in parents: return 0
        newparents = parents + [CarPose_t]
        tmphash = (0xc4efd137ad0f63c0+ librav_lcm_msgs.Vector2._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if CarPose_t._packed_fingerprint is None:
            CarPose_t._packed_fingerprint = struct.pack(">Q", CarPose_t._get_hash_recursive([]))
        return CarPose_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

