"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class CarRawSpeed_t(object):
    __slots__ = ["mtime", "count", "speed"]

    __typenames__ = ["int64_t", "int32_t", "float"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.mtime = 0
        self.count = 0
        self.speed = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(CarRawSpeed_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qif", self.mtime, self.count, self.speed))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != CarRawSpeed_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return CarRawSpeed_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = CarRawSpeed_t()
        self.mtime, self.count, self.speed = struct.unpack(">qif", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if CarRawSpeed_t in parents: return 0
        tmphash = (0x2ea6417855026f68) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if CarRawSpeed_t._packed_fingerprint is None:
            CarRawSpeed_t._packed_fingerprint = struct.pack(">Q", CarRawSpeed_t._get_hash_recursive([]))
        return CarRawSpeed_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

