"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import librav_lcm_msgs.GridWaypoint_t

class GridPath_t(object):
    __slots__ = ["pt_num", "points"]

    __typenames__ = ["int32_t", "librav_lcm_msgs.GridWaypoint_t"]

    __dimensions__ = [None, ["pt_num"]]

    def __init__(self):
        self.pt_num = 0
        self.points = []

    def encode(self):
        buf = BytesIO()
        buf.write(GridPath_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.pt_num))
        for i0 in range(self.pt_num):
            assert self.points[i0]._get_packed_fingerprint() == librav_lcm_msgs.GridWaypoint_t._get_packed_fingerprint()
            self.points[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != GridPath_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return GridPath_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = GridPath_t()
        self.pt_num = struct.unpack(">i", buf.read(4))[0]
        self.points = []
        for i0 in range(self.pt_num):
            self.points.append(librav_lcm_msgs.GridWaypoint_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if GridPath_t in parents: return 0
        newparents = parents + [GridPath_t]
        tmphash = (0x3524bf2a66017226+ librav_lcm_msgs.GridWaypoint_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if GridPath_t._packed_fingerprint is None:
            GridPath_t._packed_fingerprint = struct.pack(">Q", GridPath_t._get_hash_recursive([]))
        return GridPath_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

