"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class MapRequest_t(object):
    __slots__ = ["new_map_requested", "map_size_x", "map_size_y", "map_size_z", "map_type"]

    __typenames__ = ["boolean", "int32_t", "int32_t", "int32_t", "int8_t"]

    __dimensions__ = [None, None, None, None, None]

    def __init__(self):
        self.new_map_requested = False
        self.map_size_x = 0
        self.map_size_y = 0
        self.map_size_z = 0
        self.map_type = 0

    def encode(self):
        buf = BytesIO()
        buf.write(MapRequest_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">biiib", self.new_map_requested, self.map_size_x, self.map_size_y, self.map_size_z, self.map_type))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != MapRequest_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return MapRequest_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = MapRequest_t()
        self.new_map_requested = bool(struct.unpack('b', buf.read(1))[0])
        self.map_size_x, self.map_size_y, self.map_size_z, self.map_type = struct.unpack(">iiib", buf.read(13))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if MapRequest_t in parents: return 0
        tmphash = (0x8d93c0970f12ad5b) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if MapRequest_t._packed_fingerprint is None:
            MapRequest_t._packed_fingerprint = struct.pack(">Q", MapRequest_t._get_hash_recursive([]))
        return MapRequest_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

