"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import librav_lcm_msgs.NavSatStatus

class NavSatFix(object):
    __slots__ = ["status", "latitude", "longitude", "altitude", "position_covariance", "position_covariance_type"]

    __typenames__ = ["librav_lcm_msgs.NavSatStatus", "double", "double", "double", "double", "int8_t"]

    __dimensions__ = [None, None, None, None, [9], None]

    COVARIANCE_TYPE_UNKNOWN = 0
    COVARIANCE_TYPE_APPROXIMATED = 1
    COVARIANCE_TYPE_DIAGONAL_KNOWN = 2
    COVARIANCE_TYPE_KNOWN = 3

    def __init__(self):
        self.status = librav_lcm_msgs.NavSatStatus()
        self.latitude = 0.0
        self.longitude = 0.0
        self.altitude = 0.0
        self.position_covariance = [ 0.0 for dim0 in range(9) ]
        self.position_covariance_type = 0

    def encode(self):
        buf = BytesIO()
        buf.write(NavSatFix._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.status._get_packed_fingerprint() == librav_lcm_msgs.NavSatStatus._get_packed_fingerprint()
        self.status._encode_one(buf)
        buf.write(struct.pack(">ddd", self.latitude, self.longitude, self.altitude))
        buf.write(struct.pack('>9d', *self.position_covariance[:9]))
        buf.write(struct.pack(">b", self.position_covariance_type))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != NavSatFix._get_packed_fingerprint():
            raise ValueError("Decode error")
        return NavSatFix._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = NavSatFix()
        self.status = librav_lcm_msgs.NavSatStatus._decode_one(buf)
        self.latitude, self.longitude, self.altitude = struct.unpack(">ddd", buf.read(24))
        self.position_covariance = struct.unpack('>9d', buf.read(72))
        self.position_covariance_type = struct.unpack(">b", buf.read(1))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if NavSatFix in parents: return 0
        newparents = parents + [NavSatFix]
        tmphash = (0x60c5a36268b1a1a0+ librav_lcm_msgs.NavSatStatus._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if NavSatFix._packed_fingerprint is None:
            NavSatFix._packed_fingerprint = struct.pack(">Q", NavSatFix._get_hash_recursive([]))
        return NavSatFix._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

