"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class RawIMU10DOF(object):
    __slots__ = ["mtime", "gyro", "accel", "baro"]

    __typenames__ = ["int64_t", "float", "float", "float"]

    __dimensions__ = [None, [3], [3], None]

    def __init__(self):
        self.mtime = 0
        self.gyro = [ 0.0 for dim0 in range(3) ]
        self.accel = [ 0.0 for dim0 in range(3) ]
        self.baro = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(RawIMU10DOF._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.mtime))
        buf.write(struct.pack('>3f', *self.gyro[:3]))
        buf.write(struct.pack('>3f', *self.accel[:3]))
        buf.write(struct.pack(">f", self.baro))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != RawIMU10DOF._get_packed_fingerprint():
            raise ValueError("Decode error")
        return RawIMU10DOF._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = RawIMU10DOF()
        self.mtime = struct.unpack(">q", buf.read(8))[0]
        self.gyro = struct.unpack('>3f', buf.read(12))
        self.accel = struct.unpack('>3f', buf.read(12))
        self.baro = struct.unpack(">f", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if RawIMU10DOF in parents: return 0
        tmphash = (0xd27571225f0da045) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if RawIMU10DOF._packed_fingerprint is None:
            RawIMU10DOF._packed_fingerprint = struct.pack(">Q", RawIMU10DOF._get_hash_recursive([]))
        return RawIMU10DOF._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

