"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class SimSyncTrigger(object):
    __slots__ = ["mtime", "trigger_ready"]

    __typenames__ = ["int64_t", "boolean"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.mtime = 0
        self.trigger_ready = False

    def encode(self):
        buf = BytesIO()
        buf.write(SimSyncTrigger._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qb", self.mtime, self.trigger_ready))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != SimSyncTrigger._get_packed_fingerprint():
            raise ValueError("Decode error")
        return SimSyncTrigger._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = SimSyncTrigger()
        self.mtime = struct.unpack(">q", buf.read(8))[0]
        self.trigger_ready = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if SimSyncTrigger in parents: return 0
        tmphash = (0x24640f783aae1821) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if SimSyncTrigger._packed_fingerprint is None:
            SimSyncTrigger._packed_fingerprint = struct.pack(">Q", SimSyncTrigger._get_hash_recursive([]))
        return SimSyncTrigger._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

