"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import librav_lcm_msgs.UAVTrajectoryPoint_t

class UAVTrajectory_t(object):
    __slots__ = ["waypoint_num", "trajectory"]

    __typenames__ = ["int64_t", "librav_lcm_msgs.UAVTrajectoryPoint_t"]

    __dimensions__ = [None, ["waypoint_num"]]

    def __init__(self):
        self.waypoint_num = 0
        self.trajectory = []

    def encode(self):
        buf = BytesIO()
        buf.write(UAVTrajectory_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.waypoint_num))
        for i0 in range(self.waypoint_num):
            assert self.trajectory[i0]._get_packed_fingerprint() == librav_lcm_msgs.UAVTrajectoryPoint_t._get_packed_fingerprint()
            self.trajectory[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != UAVTrajectory_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return UAVTrajectory_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = UAVTrajectory_t()
        self.waypoint_num = struct.unpack(">q", buf.read(8))[0]
        self.trajectory = []
        for i0 in range(self.waypoint_num):
            self.trajectory.append(librav_lcm_msgs.UAVTrajectoryPoint_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if UAVTrajectory_t in parents: return 0
        newparents = parents + [UAVTrajectory_t]
        tmphash = (0xf3438377578526b8+ librav_lcm_msgs.UAVTrajectoryPoint_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if UAVTrajectory_t._packed_fingerprint is None:
            UAVTrajectory_t._packed_fingerprint = struct.pack(">Q", UAVTrajectory_t._get_hash_recursive([]))
        return UAVTrajectory_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

