env = Environment(CXXFLAGS='-g -Wall -ansi -Wno-deprecated -O3 -DNDEBUG',
                  CPPPATH=['/usr/include/vtk-5.0/','/NOBACKUP/dag/mtl4'])

vtk_libs = ['vtkCommon', 
            'vtkGraphics', 
            'vtkRendering', 
            'vtkWidgets']

env.Program('examples',
            ['examples.cpp', 'matplot.cpp'],
            LIBS=vtk_libs+['m'])
