// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#ifndef _librav_lcm_msgs_CAVMissionInfo_h
#define _librav_lcm_msgs_CAVMissionInfo_h

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifdef __cplusplus
extern "C" {
#endif

#include "lcmtypes/librav_lcm_msgs_VehicleState.h"
#include "lcmtypes/librav_lcm_msgs_VehicleState.h"
/// mission types
#define LIBRAV_LCM_MSGS_CAVMISSIONINFO_MT_NEW_MISSION_REQUEST 1
#define LIBRAV_LCM_MSGS_CAVMISSIONINFO_MT_ABORT_CURRENT_MISSION 2

typedef struct _librav_lcm_msgs_CAVMissionInfo librav_lcm_msgs_CAVMissionInfo;
struct _librav_lcm_msgs_CAVMissionInfo
{
    int64_t    id;
    int32_t    mission_type;
    librav_lcm_msgs_VehicleState start_state;
    librav_lcm_msgs_VehicleState goal_state;
};

/**
 * Create a deep copy of a librav_lcm_msgs_CAVMissionInfo.
 * When no longer needed, destroy it with librav_lcm_msgs_CAVMissionInfo_destroy()
 */
librav_lcm_msgs_CAVMissionInfo* librav_lcm_msgs_CAVMissionInfo_copy(const librav_lcm_msgs_CAVMissionInfo* to_copy);

/**
 * Destroy an instance of librav_lcm_msgs_CAVMissionInfo created by librav_lcm_msgs_CAVMissionInfo_copy()
 */
void librav_lcm_msgs_CAVMissionInfo_destroy(librav_lcm_msgs_CAVMissionInfo* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _librav_lcm_msgs_CAVMissionInfo_subscription_t librav_lcm_msgs_CAVMissionInfo_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * librav_lcm_msgs_CAVMissionInfo is received.
 */
typedef void(*librav_lcm_msgs_CAVMissionInfo_handler_t)(
    const lcm_recv_buf_t *rbuf, const char *channel,
    const librav_lcm_msgs_CAVMissionInfo *msg, void *userdata);

/**
 * Publish a message of type librav_lcm_msgs_CAVMissionInfo using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int librav_lcm_msgs_CAVMissionInfo_publish(lcm_t *lcm, const char *channel, const librav_lcm_msgs_CAVMissionInfo *msg);

/**
 * Subscribe to messages of type librav_lcm_msgs_CAVMissionInfo using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is
 *     received. This function is invoked by LCM during calls to lcm_handle()
 *     and lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
librav_lcm_msgs_CAVMissionInfo_subscription_t* librav_lcm_msgs_CAVMissionInfo_subscribe(
    lcm_t *lcm, const char *channel, librav_lcm_msgs_CAVMissionInfo_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by librav_lcm_msgs_CAVMissionInfo_subscribe()
 */
int librav_lcm_msgs_CAVMissionInfo_unsubscribe(lcm_t *lcm, librav_lcm_msgs_CAVMissionInfo_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int librav_lcm_msgs_CAVMissionInfo_subscription_set_queue_capacity(
    librav_lcm_msgs_CAVMissionInfo_subscription_t* subs, int num_messages);

/**
 * Encode a message of type librav_lcm_msgs_CAVMissionInfo into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to librav_lcm_msgs_CAVMissionInfo_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int librav_lcm_msgs_CAVMissionInfo_encode(void *buf, int offset, int maxlen, const librav_lcm_msgs_CAVMissionInfo *p);

/**
 * Decode a message of type librav_lcm_msgs_CAVMissionInfo from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with librav_lcm_msgs_CAVMissionInfo_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int librav_lcm_msgs_CAVMissionInfo_decode(const void *buf, int offset, int maxlen, librav_lcm_msgs_CAVMissionInfo *msg);

/**
 * Release resources allocated by librav_lcm_msgs_CAVMissionInfo_decode()
 * @return 0
 */
int librav_lcm_msgs_CAVMissionInfo_decode_cleanup(librav_lcm_msgs_CAVMissionInfo *p);

/**
 * Check how many bytes are required to encode a message of type librav_lcm_msgs_CAVMissionInfo
 */
int librav_lcm_msgs_CAVMissionInfo_encoded_size(const librav_lcm_msgs_CAVMissionInfo *p);

// LCM support functions. Users should not call these
int64_t __librav_lcm_msgs_CAVMissionInfo_get_hash(void);
uint64_t __librav_lcm_msgs_CAVMissionInfo_hash_recursive(const __lcm_hash_ptr *p);
int __librav_lcm_msgs_CAVMissionInfo_encode_array(
    void *buf, int offset, int maxlen, const librav_lcm_msgs_CAVMissionInfo *p, int elements);
int __librav_lcm_msgs_CAVMissionInfo_decode_array(
    const void *buf, int offset, int maxlen, librav_lcm_msgs_CAVMissionInfo *p, int elements);
int __librav_lcm_msgs_CAVMissionInfo_decode_array_cleanup(librav_lcm_msgs_CAVMissionInfo *p, int elements);
int __librav_lcm_msgs_CAVMissionInfo_encoded_array_size(const librav_lcm_msgs_CAVMissionInfo *p, int elements);
int __librav_lcm_msgs_CAVMissionInfo_clone_array(const librav_lcm_msgs_CAVMissionInfo *p, librav_lcm_msgs_CAVMissionInfo *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
