/*
 * keyboard_mapping.cpp
 *
 * Created on 7/15/24 10:41 PM
 * Description:
 *
 * Copyright (c) 2024 Ruixiang Du (rdu)
 */

#include "input_hid/details/keyboard_mapping.hpp"

#include <linux/input.h>

namespace xmotion {
std::unordered_map<int, KeyboardCode> KeyboardMapping::keycode_map = {
    {KEY_A, KeyboardCode::kA},
    {KEY_B, KeyboardCode::kB},
    {KEY_C, KeyboardCode::kC},
    {KEY_D, KeyboardCode::kD},
    {KEY_E, KeyboardCode::kE},
    {KEY_F, KeyboardCode::kF},
    {KEY_G, KeyboardCode::kG},
    {KEY_H, KeyboardCode::kH},
    {KEY_I, KeyboardCode::kI},
    {KEY_J, KeyboardCode::kJ},
    {KEY_K, KeyboardCode::kK},
    {KEY_L, KeyboardCode::kL},
    {KEY_M, KeyboardCode::kM},
    {KEY_N, KeyboardCode::kN},
    {KEY_O, KeyboardCode::kO},
    {KEY_P, KeyboardCode::kP},
    {KEY_Q, KeyboardCode::kQ},
    {KEY_R, KeyboardCode::kR},
    {KEY_S, KeyboardCode::kS},
    {KEY_T, KeyboardCode::kT},
    {KEY_U, KeyboardCode::kU},
    {KEY_V, KeyboardCode::kV},
    {KEY_W, KeyboardCode::kW},
    {KEY_X, KeyboardCode::kX},
    {KEY_Y, KeyboardCode::kY},
    {KEY_Z, KeyboardCode::kZ},
    {KEY_ESC, KeyboardCode::kEsc},
    {KEY_1, KeyboardCode::kNum1},
    {KEY_2, KeyboardCode::kNum2},
    {KEY_3, KeyboardCode::kNum3},
    {KEY_4, KeyboardCode::kNum4},
    {KEY_5, KeyboardCode::kNum5},
    {KEY_6, KeyboardCode::kNum6},
    {KEY_7, KeyboardCode::kNum7},
    {KEY_8, KeyboardCode::kNum8},
    {KEY_9, KeyboardCode::kNum9},
    {KEY_0, KeyboardCode::kNum0},
    {KEY_MINUS, KeyboardCode::kMinus},
    {KEY_EQUAL, KeyboardCode::kEqual},
    {KEY_BACKSPACE, KeyboardCode::kBackspace},
    {KEY_TAB, KeyboardCode::kTab},
    {KEY_ENTER, KeyboardCode::kEnter},
    {KEY_SPACE, KeyboardCode::kSpace},
    {KEY_CAPSLOCK, KeyboardCode::kCapsLock},
    {KEY_F1, KeyboardCode::kF1},
    {KEY_F2, KeyboardCode::kF2},
    {KEY_F3, KeyboardCode::kF3},
    {KEY_F4, KeyboardCode::kF4},
    {KEY_F5, KeyboardCode::kF5},
    {KEY_F6, KeyboardCode::kF6},
    {KEY_F7, KeyboardCode::kF7},
    {KEY_F8, KeyboardCode::kF8},
    {KEY_F9, KeyboardCode::kF9},
    {KEY_F10, KeyboardCode::kF10},
    {KEY_F11, KeyboardCode::kF11},
    {KEY_F12, KeyboardCode::kF12},
    {KEY_LEFTCTRL, KeyboardCode::kLeftCtrl},
    {KEY_RIGHTCTRL, KeyboardCode::kRightCtrl},
    {KEY_LEFTSHIFT, KeyboardCode::kLeftShift},
    {KEY_RIGHTSHIFT, KeyboardCode::kRightShift},
    {KEY_LEFTALT, KeyboardCode::kLeftAlt},
    {KEY_RIGHTALT, KeyboardCode::kRightAlt},
    {KEY_LEFT, KeyboardCode::kLeft},
    {KEY_RIGHT, KeyboardCode::kRight},
    {KEY_UP, KeyboardCode::kUp},
    {KEY_DOWN, KeyboardCode::kDown},
    {KEY_HOME, KeyboardCode::kHome},
    {KEY_END, KeyboardCode::kEnd},
    {KEY_PAGEUP, KeyboardCode::kPageUp},
    {KEY_PAGEDOWN, KeyboardCode::kPageDown}};

std::unordered_map<KeyboardCode, std::string> KeyboardMapping::keyname_map = {
    {KeyboardCode::kA, "A"},
    {KeyboardCode::kB, "B"},
    {KeyboardCode::kC, "C"},
    {KeyboardCode::kD, "D"},
    {KeyboardCode::kE, "E"},
    {KeyboardCode::kF, "F"},
    {KeyboardCode::kG, "G"},
    {KeyboardCode::kH, "H"},
    {KeyboardCode::kI, "I"},
    {KeyboardCode::kJ, "J"},
    {KeyboardCode::kK, "K"},
    {KeyboardCode::kL, "L"},
    {KeyboardCode::kM, "M"},
    {KeyboardCode::kN, "N"},
    {KeyboardCode::kO, "O"},
    {KeyboardCode::kP, "P"},
    {KeyboardCode::kQ, "Q"},
    {KeyboardCode::kR, "R"},
    {KeyboardCode::kS, "S"},
    {KeyboardCode::kT, "T"},
    {KeyboardCode::kU, "U"},
    {KeyboardCode::kV, "V"},
    {KeyboardCode::kW, "W"},
    {KeyboardCode::kX, "X"},
    {KeyboardCode::kY, "Y"},
    {KeyboardCode::kZ, "Z"},
    {KeyboardCode::kEsc, "Esc"},
    {KeyboardCode::kNum1, "1"},
    {KeyboardCode::kNum2, "2"},
    {KeyboardCode::kNum3, "3"},
    {KeyboardCode::kNum4, "4"},
    {KeyboardCode::kNum5, "5"},
    {KeyboardCode::kNum6, "6"},
    {KeyboardCode::kNum7, "7"},
    {KeyboardCode::kNum8, "8"},
    {KeyboardCode::kNum9, "9"},
    {KeyboardCode::kNum0, "0"},
    {KeyboardCode::kMinus, "-"},
    {KeyboardCode::kEqual, "="},
    {KeyboardCode::kBackspace, "Backspace"},
    {KeyboardCode::kTab, "Tab"},
    {KeyboardCode::kEnter, "Enter"},
    {KeyboardCode::kSpace, "Space"},
    {KeyboardCode::kCapsLock, "CapsLock"},
    {KeyboardCode::kF1, "F1"},
    {KeyboardCode::kF2, "F2"},
    {KeyboardCode::kF3, "F3"},
    {KeyboardCode::kF4, "F4"},
    {KeyboardCode::kF5, "F5"},
    {KeyboardCode::kF6, "F6"},
    {KeyboardCode::kF7, "F7"},
    {KeyboardCode::kF8, "F8"},
    {KeyboardCode::kF9, "F9"},
    {KeyboardCode::kF10, "F10"},
    {KeyboardCode::kF11, "F11"},
    {KeyboardCode::kF12, "F12"},
    {KeyboardCode::kLeftCtrl, "LeftCtrl"},
    {KeyboardCode::kRightCtrl, "RightCtrl"},
    {KeyboardCode::kLeftShift, "LeftShift"},
    {KeyboardCode::kRightShift, "RightShift"},
    {KeyboardCode::kLeftAlt, "LeftAlt"},
    {KeyboardCode::kRightAlt, "RightAlt"},
    {KeyboardCode::kLeft, "Left"},
    {KeyboardCode::kRight, "Right"},
    {KeyboardCode::kUp, "Up"},
    {KeyboardCode::kDown, "Down"},
    {KeyboardCode::kHome, "Home"},
    {KeyboardCode::kEnd, "End"},
    {KeyboardCode::kPageUp, "PageUp"},
    {KeyboardCode::kPageDown, "PageDown"}};

std::unordered_map<std::string, KeyboardCode>
    KeyboardMapping::keyname_to_keycode_map = {
        {"A", KeyboardCode::kA},
        {"B", KeyboardCode::kB},
        {"C", KeyboardCode::kC},
        {"D", KeyboardCode::kD},
        {"E", KeyboardCode::kE},
        {"F", KeyboardCode::kF},
        {"G", KeyboardCode::kG},
        {"H", KeyboardCode::kH},
        {"I", KeyboardCode::kI},
        {"J", KeyboardCode::kJ},
        {"K", KeyboardCode::kK},
        {"L", KeyboardCode::kL},
        {"M", KeyboardCode::kM},
        {"N", KeyboardCode::kN},
        {"O", KeyboardCode::kO},
        {"P", KeyboardCode::kP},
        {"Q", KeyboardCode::kQ},
        {"R", KeyboardCode::kR},
        {"S", KeyboardCode::kS},
        {"T", KeyboardCode::kT},
        {"U", KeyboardCode::kU},
        {"V", KeyboardCode::kV},
        {"W", KeyboardCode::kW},
        {"X", KeyboardCode::kX},
        {"Y", KeyboardCode::kY},
        {"Z", KeyboardCode::kZ},
        {"Esc", KeyboardCode::kEsc},
        {"1", KeyboardCode::kNum1},
        {"2", KeyboardCode::kNum2},
        {"3", KeyboardCode::kNum3},
        {"4", KeyboardCode::kNum4},
        {"5", KeyboardCode::kNum5},
        {"6", KeyboardCode::kNum6},
        {"7", KeyboardCode::kNum7},
        {"8", KeyboardCode::kNum8},
        {"9", KeyboardCode::kNum9},
        {"0", KeyboardCode::kNum0},
        {"-", KeyboardCode::kMinus},
        {"=", KeyboardCode::kEqual},
        {"Backspace", KeyboardCode::kBackspace},
        {"Tab", KeyboardCode::kTab},
        {"Enter", KeyboardCode::kEnter},
        {"Space", KeyboardCode::kSpace},
        {"CapsLock", KeyboardCode::kCapsLock},
        {"F1", KeyboardCode::kF1},
        {"F2", KeyboardCode::kF2},
        {"F3", KeyboardCode::kF3},
        {"F4", KeyboardCode::kF4},
        {"F5", KeyboardCode::kF5},
        {"F6", KeyboardCode::kF6},
        {"F7", KeyboardCode::kF7},
        {"F8", KeyboardCode::kF8},
        {"F9", KeyboardCode::kF9},
        {"F10", KeyboardCode::kF10},
        {"F11", KeyboardCode::kF11},
        {"F12", KeyboardCode::kF12},
        {"LeftCtrl", KeyboardCode::kLeftCtrl},
        {"RightCtrl", KeyboardCode::kRightCtrl},
        {"LeftShift", KeyboardCode::kLeftShift},
        {"RightShift", KeyboardCode::kRightShift},
        {"LeftAlt", KeyboardCode::kLeftAlt},
        {"RightAlt", KeyboardCode::kRightAlt},
        {"Left", KeyboardCode::kLeft},
        {"Right", KeyboardCode::kRight},
        {"Up", KeyboardCode::kUp},
        {"Down", KeyboardCode::kDown},
        {"Home", KeyboardCode::kHome},
        {"End", KeyboardCode::kEnd},
        {"PageUp", KeyboardCode::kPageUp},
        {"PageDown", KeyboardCode::kPageDown}};

std::string KeyboardMapping::GetKeyName(KeyboardCode code) {
  if (keyname_map.find(code) == keyname_map.end()) return "UnknownKey";
  return KeyboardMapping::keyname_map[code];
}

KeyboardCode KeyboardMapping::GetKeyCode(const std::string& key_name) {
  if (keyname_to_keycode_map.find(key_name) == keyname_to_keycode_map.end()) {
    return KeyboardCode::kUnknown;
  }
  return keyname_to_keycode_map[key_name];
}
}  // namespace xmotion