/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __srcl_lcm_msgs_PolyCurveSegment_t_hpp__
#define __srcl_lcm_msgs_PolyCurveSegment_t_hpp__

#include <lcm/lcm_coretypes.h>

#include <vector>

namespace srcl_lcm_msgs
{

class PolyCurveSegment_t
{
    public:
        int64_t    coeffsize_x;

        int64_t    coeffsize_y;

        int64_t    coeffsize_z;

        int64_t    coeffsize_yaw;

        std::vector< double > coeffs_x;

        std::vector< double > coeffs_y;

        std::vector< double > coeffs_z;

        std::vector< double > coeffs_yaw;

        double     t_start;

        double     t_end;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "PolyCurveSegment_t"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int PolyCurveSegment_t::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = (int64_t)getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int PolyCurveSegment_t::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int PolyCurveSegment_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t PolyCurveSegment_t::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* PolyCurveSegment_t::getTypeName()
{
    return "PolyCurveSegment_t";
}

int PolyCurveSegment_t::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->coeffsize_x, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->coeffsize_y, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->coeffsize_z, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->coeffsize_yaw, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->coeffsize_x > 0) {
        tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->coeffs_x[0], this->coeffsize_x);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->coeffsize_y > 0) {
        tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->coeffs_y[0], this->coeffsize_y);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->coeffsize_z > 0) {
        tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->coeffs_z[0], this->coeffsize_z);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->coeffsize_yaw > 0) {
        tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->coeffs_yaw[0], this->coeffsize_yaw);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->t_start, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->t_end, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int PolyCurveSegment_t::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->coeffsize_x, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->coeffsize_y, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->coeffsize_z, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->coeffsize_yaw, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->coeffsize_x) {
        this->coeffs_x.resize(this->coeffsize_x);
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->coeffs_x[0], this->coeffsize_x);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->coeffsize_y) {
        this->coeffs_y.resize(this->coeffsize_y);
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->coeffs_y[0], this->coeffsize_y);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->coeffsize_z) {
        this->coeffs_z.resize(this->coeffsize_z);
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->coeffs_z[0], this->coeffsize_z);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->coeffsize_yaw) {
        this->coeffs_yaw.resize(this->coeffsize_yaw);
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->coeffs_yaw[0], this->coeffsize_yaw);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->t_start, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->t_end, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int PolyCurveSegment_t::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, this->coeffsize_x);
    enc_size += __double_encoded_array_size(NULL, this->coeffsize_y);
    enc_size += __double_encoded_array_size(NULL, this->coeffsize_z);
    enc_size += __double_encoded_array_size(NULL, this->coeffsize_yaw);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    return enc_size;
}

uint64_t PolyCurveSegment_t::_computeHash(const __lcm_hash_ptr *)
{
    uint64_t hash = 0x83be790aed767d0dLL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
