"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class MissionInfo_t(object):
    __slots__ = ["dist_to_goal", "next_wp_id", "trajectory_id"]

    __typenames__ = ["double", "int32_t", "int64_t"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.dist_to_goal = 0.0
        self.next_wp_id = 0
        self.trajectory_id = 0

    def encode(self):
        buf = BytesIO()
        buf.write(MissionInfo_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">diq", self.dist_to_goal, self.next_wp_id, self.trajectory_id))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != MissionInfo_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return MissionInfo_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = MissionInfo_t()
        self.dist_to_goal, self.next_wp_id, self.trajectory_id = struct.unpack(">diq", buf.read(20))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if MissionInfo_t in parents: return 0
        tmphash = (0x51f3e950a793847c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if MissionInfo_t._packed_fingerprint is None:
            MissionInfo_t._packed_fingerprint = struct.pack(">Q", MissionInfo_t._get_hash_recursive([]))
        return MissionInfo_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

