"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class NewDataReady_t(object):
    __slots__ = ["new_data_ready_"]

    __typenames__ = ["boolean"]

    __dimensions__ = [None]

    def __init__(self):
        self.new_data_ready_ = False

    def encode(self):
        buf = BytesIO()
        buf.write(NewDataReady_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.new_data_ready_))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != NewDataReady_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return NewDataReady_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = NewDataReady_t()
        self.new_data_ready_ = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if NewDataReady_t in parents: return 0
        tmphash = (0x1615e79a08e440f1) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if NewDataReady_t._packed_fingerprint is None:
            NewDataReady_t._packed_fingerprint = struct.pack(">Q", NewDataReady_t._get_hash_recursive([]))
        return NewDataReady_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

