"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class Vertex_t(object):
    __slots__ = ["id", "position"]

    def __init__(self):
        self.id = 0
        self.position = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(Vertex_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.id))
        buf.write(struct.pack('>3f', *self.position[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Vertex_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Vertex_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = Vertex_t()
        self.id = struct.unpack(">q", buf.read(8))[0]
        self.position = struct.unpack('>3f', buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if Vertex_t in parents: return 0
        tmphash = (0xebb7afb0e54cf3b4) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if Vertex_t._packed_fingerprint is None:
            Vertex_t._packed_fingerprint = struct.pack(">Q", Vertex_t._get_hash_recursive([]))
        return Vertex_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

