/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package srcl_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class LaserScanPoints_t implements lcm.lcm.LCMEncodable
{
    public srcl_msgs.Pose_t trans_sensor2world;
    public long point_num;
    public srcl_msgs.Point3Df_t points[];
 
    public LaserScanPoints_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x503d7b918ac7be34L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(srcl_msgs.LaserScanPoints_t.class))
            return 0L;
 
        classes.add(srcl_msgs.LaserScanPoints_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + srcl_msgs.Pose_t._hashRecursive(classes)
             + srcl_msgs.Point3Df_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.trans_sensor2world._encodeRecursive(outs); 
 
        outs.writeLong(this.point_num); 
 
        for (int a = 0; a < this.point_num; a++) {
            this.points[a]._encodeRecursive(outs); 
        }
 
    }
 
    public LaserScanPoints_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public LaserScanPoints_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static srcl_msgs.LaserScanPoints_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        srcl_msgs.LaserScanPoints_t o = new srcl_msgs.LaserScanPoints_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.trans_sensor2world = srcl_msgs.Pose_t._decodeRecursiveFactory(ins);
 
        this.point_num = ins.readLong();
 
        this.points = new srcl_msgs.Point3Df_t[(int) point_num];
        for (int a = 0; a < this.point_num; a++) {
            this.points[a] = srcl_msgs.Point3Df_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public srcl_msgs.LaserScanPoints_t copy()
    {
        srcl_msgs.LaserScanPoints_t outobj = new srcl_msgs.LaserScanPoints_t();
        outobj.trans_sensor2world = this.trans_sensor2world.copy();
 
        outobj.point_num = this.point_num;
 
        outobj.points = new srcl_msgs.Point3Df_t[(int) point_num];
        for (int a = 0; a < this.point_num; a++) {
            outobj.points[a] = this.points[a].copy();
        }
 
        return outobj;
    }
 
}

