/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package srcl_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class UAVTrajectoryPoint_t implements lcm.lcm.LCMEncodable
{
    public boolean point_empty;
    public float positions[];
    public float velocities[];
    public float accelerations[];
    public float yaw;
    public long duration;
 
    public UAVTrajectoryPoint_t()
    {
        positions = new float[3];
        velocities = new float[3];
        accelerations = new float[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x7573d937233fe433L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(srcl_msgs.UAVTrajectoryPoint_t.class))
            return 0L;
 
        classes.add(srcl_msgs.UAVTrajectoryPoint_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte( this.point_empty ? 1 : 0); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.positions[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.velocities[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.accelerations[a]); 
        }
 
        outs.writeFloat(this.yaw); 
 
        outs.writeLong(this.duration); 
 
    }
 
    public UAVTrajectoryPoint_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public UAVTrajectoryPoint_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static srcl_msgs.UAVTrajectoryPoint_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        srcl_msgs.UAVTrajectoryPoint_t o = new srcl_msgs.UAVTrajectoryPoint_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.point_empty = ins.readByte()!=0;
 
        this.positions = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.positions[a] = ins.readFloat();
        }
 
        this.velocities = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.velocities[a] = ins.readFloat();
        }
 
        this.accelerations = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.accelerations[a] = ins.readFloat();
        }
 
        this.yaw = ins.readFloat();
 
        this.duration = ins.readLong();
 
    }
 
    public srcl_msgs.UAVTrajectoryPoint_t copy()
    {
        srcl_msgs.UAVTrajectoryPoint_t outobj = new srcl_msgs.UAVTrajectoryPoint_t();
        outobj.point_empty = this.point_empty;
 
        outobj.positions = new float[(int) 3];
        System.arraycopy(this.positions, 0, outobj.positions, 0, 3); 
        outobj.velocities = new float[(int) 3];
        System.arraycopy(this.velocities, 0, outobj.velocities, 0, 3); 
        outobj.accelerations = new float[(int) 3];
        System.arraycopy(this.accelerations, 0, outobj.accelerations, 0, 3); 
        outobj.yaw = this.yaw;
 
        outobj.duration = this.duration;
 
        return outobj;
    }
 
}

