/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __srcl_lcm_msgs_PolynomialCurve_t_hpp__
#define __srcl_lcm_msgs_PolynomialCurve_t_hpp__

#include <vector>
#include "lcmtypes/srcl_lcm_msgs/PolyCurveSegment_t.hpp"
#include "lcmtypes/srcl_lcm_msgs/WayPoint_t.hpp"
#include "lcmtypes/srcl_lcm_msgs/TimeStamp_t.hpp"

namespace srcl_lcm_msgs
{

class PolynomialCurve_t
{
    public:
        int64_t    seg_num;

        std::vector< srcl_lcm_msgs::PolyCurveSegment_t > segments;

        int32_t    wp_num;

        std::vector< srcl_lcm_msgs::WayPoint_t > waypoints;

        srcl_lcm_msgs::TimeStamp_t start_time;

        int64_t    trajectory_id;

        float      scaling_factor;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "PolynomialCurve_t"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int PolynomialCurve_t::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = (int64_t)getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int PolynomialCurve_t::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int PolynomialCurve_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t PolynomialCurve_t::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* PolynomialCurve_t::getTypeName()
{
    return "PolynomialCurve_t";
}

int PolynomialCurve_t::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->seg_num, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->seg_num; a0++) {
        tlen = this->segments[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->wp_num, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->wp_num; a0++) {
        tlen = this->waypoints[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = this->start_time._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->trajectory_id, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->scaling_factor, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int PolynomialCurve_t::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->seg_num, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->segments.resize(this->seg_num);
    for (int a0 = 0; a0 < this->seg_num; a0++) {
        tlen = this->segments[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->wp_num, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->waypoints.resize(this->wp_num);
    for (int a0 = 0; a0 < this->wp_num; a0++) {
        tlen = this->waypoints[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = this->start_time._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->trajectory_id, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->scaling_factor, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int PolynomialCurve_t::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->seg_num; a0++) {
        enc_size += this->segments[a0]._getEncodedSizeNoHash();
    }
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->wp_num; a0++) {
        enc_size += this->waypoints[a0]._getEncodedSizeNoHash();
    }
    enc_size += this->start_time._getEncodedSizeNoHash();
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    return enc_size;
}

uint64_t PolynomialCurve_t::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == PolynomialCurve_t::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, (void*)PolynomialCurve_t::getHash };

    uint64_t hash = 0xb6932b5031a4ffe5LL +
         srcl_lcm_msgs::PolyCurveSegment_t::_computeHash(&cp) +
         srcl_lcm_msgs::WayPoint_t::_computeHash(&cp) +
         srcl_lcm_msgs::TimeStamp_t::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
