/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package librav_lcm_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class CarRawSpeed_t implements lcm.lcm.LCMEncodable
{
    public long mtime;
    public int count;
    public float speed;
 
    public CarRawSpeed_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x2ea6417855026f68L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(librav_lcm_msgs.CarRawSpeed_t.class))
            return 0L;
 
        classes.add(librav_lcm_msgs.CarRawSpeed_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.mtime); 
 
        outs.writeInt(this.count); 
 
        outs.writeFloat(this.speed); 
 
    }
 
    public CarRawSpeed_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public CarRawSpeed_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static librav_lcm_msgs.CarRawSpeed_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        librav_lcm_msgs.CarRawSpeed_t o = new librav_lcm_msgs.CarRawSpeed_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.mtime = ins.readLong();
 
        this.count = ins.readInt();
 
        this.speed = ins.readFloat();
 
    }
 
    public librav_lcm_msgs.CarRawSpeed_t copy()
    {
        librav_lcm_msgs.CarRawSpeed_t outobj = new librav_lcm_msgs.CarRawSpeed_t();
        outobj.mtime = this.mtime;
 
        outobj.count = this.count;
 
        outobj.speed = this.speed;
 
        return outobj;
    }
 
}

