/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package librav_lcm_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class Edge_t implements lcm.lcm.LCMEncodable
{
    public long id_start;
    public long id_end;
 
    public Edge_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xda1b389bca30b83cL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(librav_lcm_msgs.Edge_t.class))
            return 0L;
 
        classes.add(librav_lcm_msgs.Edge_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.id_start); 
 
        outs.writeLong(this.id_end); 
 
    }
 
    public Edge_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public Edge_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static librav_lcm_msgs.Edge_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        librav_lcm_msgs.Edge_t o = new librav_lcm_msgs.Edge_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.id_start = ins.readLong();
 
        this.id_end = ins.readLong();
 
    }
 
    public librav_lcm_msgs.Edge_t copy()
    {
        librav_lcm_msgs.Edge_t outobj = new librav_lcm_msgs.Edge_t();
        outobj.id_start = this.id_start;
 
        outobj.id_end = this.id_end;
 
        return outobj;
    }
 
}

