/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package librav_lcm_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class GridPath_t implements lcm.lcm.LCMEncodable
{
    public int pt_num;
    public librav_lcm_msgs.GridWaypoint_t points[];
 
    public GridPath_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x3524bf2a66017226L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(librav_lcm_msgs.GridPath_t.class))
            return 0L;
 
        classes.add(librav_lcm_msgs.GridPath_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + librav_lcm_msgs.GridWaypoint_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.pt_num); 
 
        for (int a = 0; a < this.pt_num; a++) {
            this.points[a]._encodeRecursive(outs); 
        }
 
    }
 
    public GridPath_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public GridPath_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static librav_lcm_msgs.GridPath_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        librav_lcm_msgs.GridPath_t o = new librav_lcm_msgs.GridPath_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.pt_num = ins.readInt();
 
        this.points = new librav_lcm_msgs.GridWaypoint_t[(int) pt_num];
        for (int a = 0; a < this.pt_num; a++) {
            this.points[a] = librav_lcm_msgs.GridWaypoint_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public librav_lcm_msgs.GridPath_t copy()
    {
        librav_lcm_msgs.GridPath_t outobj = new librav_lcm_msgs.GridPath_t();
        outobj.pt_num = this.pt_num;
 
        outobj.points = new librav_lcm_msgs.GridWaypoint_t[(int) pt_num];
        for (int a = 0; a < this.pt_num; a++) {
            outobj.points[a] = this.points[a].copy();
        }
 
        return outobj;
    }
 
}

