/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package librav_lcm_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class IMU implements lcm.lcm.LCMEncodable
{
    public long mtime;
    public librav_lcm_msgs.Quaternion orientation;
    public double orientation_covariance[];
    public librav_lcm_msgs.Vector3 angular_velocity;
    public double angular_velocity_covariance[];
    public librav_lcm_msgs.Vector3 linear_acceleration;
    public double linear_acceleration_covariance[];
 
    public IMU()
    {
        orientation_covariance = new double[9];
        angular_velocity_covariance = new double[9];
        linear_acceleration_covariance = new double[9];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xac2e31fe8e135e97L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(librav_lcm_msgs.IMU.class))
            return 0L;
 
        classes.add(librav_lcm_msgs.IMU.class);
        long hash = LCM_FINGERPRINT_BASE
             + librav_lcm_msgs.Quaternion._hashRecursive(classes)
             + librav_lcm_msgs.Vector3._hashRecursive(classes)
             + librav_lcm_msgs.Vector3._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.mtime); 
 
        this.orientation._encodeRecursive(outs); 
 
        for (int a = 0; a < 9; a++) {
            outs.writeDouble(this.orientation_covariance[a]); 
        }
 
        this.angular_velocity._encodeRecursive(outs); 
 
        for (int a = 0; a < 9; a++) {
            outs.writeDouble(this.angular_velocity_covariance[a]); 
        }
 
        this.linear_acceleration._encodeRecursive(outs); 
 
        for (int a = 0; a < 9; a++) {
            outs.writeDouble(this.linear_acceleration_covariance[a]); 
        }
 
    }
 
    public IMU(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public IMU(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static librav_lcm_msgs.IMU _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        librav_lcm_msgs.IMU o = new librav_lcm_msgs.IMU();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.mtime = ins.readLong();
 
        this.orientation = librav_lcm_msgs.Quaternion._decodeRecursiveFactory(ins);
 
        this.orientation_covariance = new double[(int) 9];
        for (int a = 0; a < 9; a++) {
            this.orientation_covariance[a] = ins.readDouble();
        }
 
        this.angular_velocity = librav_lcm_msgs.Vector3._decodeRecursiveFactory(ins);
 
        this.angular_velocity_covariance = new double[(int) 9];
        for (int a = 0; a < 9; a++) {
            this.angular_velocity_covariance[a] = ins.readDouble();
        }
 
        this.linear_acceleration = librav_lcm_msgs.Vector3._decodeRecursiveFactory(ins);
 
        this.linear_acceleration_covariance = new double[(int) 9];
        for (int a = 0; a < 9; a++) {
            this.linear_acceleration_covariance[a] = ins.readDouble();
        }
 
    }
 
    public librav_lcm_msgs.IMU copy()
    {
        librav_lcm_msgs.IMU outobj = new librav_lcm_msgs.IMU();
        outobj.mtime = this.mtime;
 
        outobj.orientation = this.orientation.copy();
 
        outobj.orientation_covariance = new double[(int) 9];
        System.arraycopy(this.orientation_covariance, 0, outobj.orientation_covariance, 0, 9); 
        outobj.angular_velocity = this.angular_velocity.copy();
 
        outobj.angular_velocity_covariance = new double[(int) 9];
        System.arraycopy(this.angular_velocity_covariance, 0, outobj.angular_velocity_covariance, 0, 9); 
        outobj.linear_acceleration = this.linear_acceleration.copy();
 
        outobj.linear_acceleration_covariance = new double[(int) 9];
        System.arraycopy(this.linear_acceleration_covariance, 0, outobj.linear_acceleration_covariance, 0, 9); 
        return outobj;
    }
 
}

