/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package librav_lcm_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class LaserScanPoints_t implements lcm.lcm.LCMEncodable
{
    public librav_lcm_msgs.Pose_t trans_sensor2world;
    public long point_num;
    public librav_lcm_msgs.Point3Df_t points[];
    public librav_lcm_msgs.QuadrotorTransform pose;
 
    public LaserScanPoints_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x41cb5b1499974f70L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(librav_lcm_msgs.LaserScanPoints_t.class))
            return 0L;
 
        classes.add(librav_lcm_msgs.LaserScanPoints_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + librav_lcm_msgs.Pose_t._hashRecursive(classes)
             + librav_lcm_msgs.Point3Df_t._hashRecursive(classes)
             + librav_lcm_msgs.QuadrotorTransform._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.trans_sensor2world._encodeRecursive(outs); 
 
        outs.writeLong(this.point_num); 
 
        for (int a = 0; a < this.point_num; a++) {
            this.points[a]._encodeRecursive(outs); 
        }
 
        this.pose._encodeRecursive(outs); 
 
    }
 
    public LaserScanPoints_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public LaserScanPoints_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static librav_lcm_msgs.LaserScanPoints_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        librav_lcm_msgs.LaserScanPoints_t o = new librav_lcm_msgs.LaserScanPoints_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.trans_sensor2world = librav_lcm_msgs.Pose_t._decodeRecursiveFactory(ins);
 
        this.point_num = ins.readLong();
 
        this.points = new librav_lcm_msgs.Point3Df_t[(int) point_num];
        for (int a = 0; a < this.point_num; a++) {
            this.points[a] = librav_lcm_msgs.Point3Df_t._decodeRecursiveFactory(ins);
        }
 
        this.pose = librav_lcm_msgs.QuadrotorTransform._decodeRecursiveFactory(ins);
 
    }
 
    public librav_lcm_msgs.LaserScanPoints_t copy()
    {
        librav_lcm_msgs.LaserScanPoints_t outobj = new librav_lcm_msgs.LaserScanPoints_t();
        outobj.trans_sensor2world = this.trans_sensor2world.copy();
 
        outobj.point_num = this.point_num;
 
        outobj.points = new librav_lcm_msgs.Point3Df_t[(int) point_num];
        for (int a = 0; a < this.point_num; a++) {
            outobj.points[a] = this.points[a].copy();
        }
 
        outobj.pose = this.pose.copy();
 
        return outobj;
    }
 
}

