/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package librav_lcm_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class Map_t implements lcm.lcm.LCMEncodable
{
    public int size_x;
    public int size_y;
    public int size_z;
    public long cell_num;
    public librav_lcm_msgs.Cell_t cells[];
    public long voxel_num;
    public librav_lcm_msgs.Voxel_t voxels[];
 
    public Map_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x46a945be7dfca6b8L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(librav_lcm_msgs.Map_t.class))
            return 0L;
 
        classes.add(librav_lcm_msgs.Map_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + librav_lcm_msgs.Cell_t._hashRecursive(classes)
             + librav_lcm_msgs.Voxel_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.size_x); 
 
        outs.writeInt(this.size_y); 
 
        outs.writeInt(this.size_z); 
 
        outs.writeLong(this.cell_num); 
 
        for (int a = 0; a < this.cell_num; a++) {
            this.cells[a]._encodeRecursive(outs); 
        }
 
        outs.writeLong(this.voxel_num); 
 
        for (int a = 0; a < this.voxel_num; a++) {
            this.voxels[a]._encodeRecursive(outs); 
        }
 
    }
 
    public Map_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public Map_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static librav_lcm_msgs.Map_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        librav_lcm_msgs.Map_t o = new librav_lcm_msgs.Map_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.size_x = ins.readInt();
 
        this.size_y = ins.readInt();
 
        this.size_z = ins.readInt();
 
        this.cell_num = ins.readLong();
 
        this.cells = new librav_lcm_msgs.Cell_t[(int) cell_num];
        for (int a = 0; a < this.cell_num; a++) {
            this.cells[a] = librav_lcm_msgs.Cell_t._decodeRecursiveFactory(ins);
        }
 
        this.voxel_num = ins.readLong();
 
        this.voxels = new librav_lcm_msgs.Voxel_t[(int) voxel_num];
        for (int a = 0; a < this.voxel_num; a++) {
            this.voxels[a] = librav_lcm_msgs.Voxel_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public librav_lcm_msgs.Map_t copy()
    {
        librav_lcm_msgs.Map_t outobj = new librav_lcm_msgs.Map_t();
        outobj.size_x = this.size_x;
 
        outobj.size_y = this.size_y;
 
        outobj.size_z = this.size_z;
 
        outobj.cell_num = this.cell_num;
 
        outobj.cells = new librav_lcm_msgs.Cell_t[(int) cell_num];
        for (int a = 0; a < this.cell_num; a++) {
            outobj.cells[a] = this.cells[a].copy();
        }
 
        outobj.voxel_num = this.voxel_num;
 
        outobj.voxels = new librav_lcm_msgs.Voxel_t[(int) voxel_num];
        for (int a = 0; a < this.voxel_num; a++) {
            outobj.voxels[a] = this.voxels[a].copy();
        }
 
        return outobj;
    }
 
}

