/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package librav_lcm_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class MissionInfo_t implements lcm.lcm.LCMEncodable
{
    public double dist_to_goal;
    public int next_wp_id;
    public long trajectory_id;
 
    public MissionInfo_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x51f3e950a793847cL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(librav_lcm_msgs.MissionInfo_t.class))
            return 0L;
 
        classes.add(librav_lcm_msgs.MissionInfo_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeDouble(this.dist_to_goal); 
 
        outs.writeInt(this.next_wp_id); 
 
        outs.writeLong(this.trajectory_id); 
 
    }
 
    public MissionInfo_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public MissionInfo_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static librav_lcm_msgs.MissionInfo_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        librav_lcm_msgs.MissionInfo_t o = new librav_lcm_msgs.MissionInfo_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.dist_to_goal = ins.readDouble();
 
        this.next_wp_id = ins.readInt();
 
        this.trajectory_id = ins.readLong();
 
    }
 
    public librav_lcm_msgs.MissionInfo_t copy()
    {
        librav_lcm_msgs.MissionInfo_t outobj = new librav_lcm_msgs.MissionInfo_t();
        outobj.dist_to_goal = this.dist_to_goal;
 
        outobj.next_wp_id = this.next_wp_id;
 
        outobj.trajectory_id = this.trajectory_id;
 
        return outobj;
    }
 
}

