/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package librav_lcm_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class QuadPose_t implements lcm.lcm.LCMEncodable
{
    public int x;
    public int y;
    public int z;
    public double yaw;
    public int id;
 
    public QuadPose_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x4653599c0fbb155bL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(librav_lcm_msgs.QuadPose_t.class))
            return 0L;
 
        classes.add(librav_lcm_msgs.QuadPose_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.x); 
 
        outs.writeInt(this.y); 
 
        outs.writeInt(this.z); 
 
        outs.writeDouble(this.yaw); 
 
        outs.writeInt(this.id); 
 
    }
 
    public QuadPose_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public QuadPose_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static librav_lcm_msgs.QuadPose_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        librav_lcm_msgs.QuadPose_t o = new librav_lcm_msgs.QuadPose_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.x = ins.readInt();
 
        this.y = ins.readInt();
 
        this.z = ins.readInt();
 
        this.yaw = ins.readDouble();
 
        this.id = ins.readInt();
 
    }
 
    public librav_lcm_msgs.QuadPose_t copy()
    {
        librav_lcm_msgs.QuadPose_t outobj = new librav_lcm_msgs.QuadPose_t();
        outobj.x = this.x;
 
        outobj.y = this.y;
 
        outobj.z = this.z;
 
        outobj.yaw = this.yaw;
 
        outobj.id = this.id;
 
        return outobj;
    }
 
}

