/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package librav_lcm_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class RawAccel implements lcm.lcm.LCMEncodable
{
    public long mtime;
    public float accel[];
 
    public RawAccel()
    {
        accel = new float[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x1317644918cca9a1L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(librav_lcm_msgs.RawAccel.class))
            return 0L;
 
        classes.add(librav_lcm_msgs.RawAccel.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.mtime); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.accel[a]); 
        }
 
    }
 
    public RawAccel(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public RawAccel(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static librav_lcm_msgs.RawAccel _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        librav_lcm_msgs.RawAccel o = new librav_lcm_msgs.RawAccel();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.mtime = ins.readLong();
 
        this.accel = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.accel[a] = ins.readFloat();
        }
 
    }
 
    public librav_lcm_msgs.RawAccel copy()
    {
        librav_lcm_msgs.RawAccel outobj = new librav_lcm_msgs.RawAccel();
        outobj.mtime = this.mtime;
 
        outobj.accel = new float[(int) 3];
        System.arraycopy(this.accel, 0, outobj.accel, 0, 3); 
        return outobj;
    }
 
}

