/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package librav_lcm_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class SimSyncTrigger implements lcm.lcm.LCMEncodable
{
    public long mtime;
    public boolean trigger_ready;
 
    public SimSyncTrigger()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x24640f783aae1821L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(librav_lcm_msgs.SimSyncTrigger.class))
            return 0L;
 
        classes.add(librav_lcm_msgs.SimSyncTrigger.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.mtime); 
 
        outs.writeByte( this.trigger_ready ? 1 : 0); 
 
    }
 
    public SimSyncTrigger(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public SimSyncTrigger(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static librav_lcm_msgs.SimSyncTrigger _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        librav_lcm_msgs.SimSyncTrigger o = new librav_lcm_msgs.SimSyncTrigger();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.mtime = ins.readLong();
 
        this.trigger_ready = ins.readByte()!=0;
 
    }
 
    public librav_lcm_msgs.SimSyncTrigger copy()
    {
        librav_lcm_msgs.SimSyncTrigger outobj = new librav_lcm_msgs.SimSyncTrigger();
        outobj.mtime = this.mtime;
 
        outobj.trigger_ready = this.trigger_ready;
 
        return outobj;
    }
 
}

