/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package librav_lcm_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class VehicleEstimations implements lcm.lcm.LCMEncodable
{
    public long vehicle_num;
    public librav_lcm_msgs.VehicleState estimations[];
 
    public VehicleEstimations()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x5266695341483a6fL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(librav_lcm_msgs.VehicleEstimations.class))
            return 0L;
 
        classes.add(librav_lcm_msgs.VehicleEstimations.class);
        long hash = LCM_FINGERPRINT_BASE
             + librav_lcm_msgs.VehicleState._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.vehicle_num); 
 
        for (int a = 0; a < this.vehicle_num; a++) {
            this.estimations[a]._encodeRecursive(outs); 
        }
 
    }
 
    public VehicleEstimations(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public VehicleEstimations(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static librav_lcm_msgs.VehicleEstimations _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        librav_lcm_msgs.VehicleEstimations o = new librav_lcm_msgs.VehicleEstimations();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.vehicle_num = ins.readLong();
 
        this.estimations = new librav_lcm_msgs.VehicleState[(int) vehicle_num];
        for (int a = 0; a < this.vehicle_num; a++) {
            this.estimations[a] = librav_lcm_msgs.VehicleState._decodeRecursiveFactory(ins);
        }
 
    }
 
    public librav_lcm_msgs.VehicleEstimations copy()
    {
        librav_lcm_msgs.VehicleEstimations outobj = new librav_lcm_msgs.VehicleEstimations();
        outobj.vehicle_num = this.vehicle_num;
 
        outobj.estimations = new librav_lcm_msgs.VehicleState[(int) vehicle_num];
        for (int a = 0; a < this.vehicle_num; a++) {
            outobj.estimations[a] = this.estimations[a].copy();
        }
 
        return outobj;
    }
 
}

