/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package librav_lcm_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class Voxel_t implements lcm.lcm.LCMEncodable
{
    public int id;
    public int pos_x;
    public int pos_y;
    public int pos_z;
    public boolean occupied;
 
    public Voxel_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x305375bcf9de1945L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(librav_lcm_msgs.Voxel_t.class))
            return 0L;
 
        classes.add(librav_lcm_msgs.Voxel_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.id); 
 
        outs.writeInt(this.pos_x); 
 
        outs.writeInt(this.pos_y); 
 
        outs.writeInt(this.pos_z); 
 
        outs.writeByte( this.occupied ? 1 : 0); 
 
    }
 
    public Voxel_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public Voxel_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static librav_lcm_msgs.Voxel_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        librav_lcm_msgs.Voxel_t o = new librav_lcm_msgs.Voxel_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.id = ins.readInt();
 
        this.pos_x = ins.readInt();
 
        this.pos_y = ins.readInt();
 
        this.pos_z = ins.readInt();
 
        this.occupied = ins.readByte()!=0;
 
    }
 
    public librav_lcm_msgs.Voxel_t copy()
    {
        librav_lcm_msgs.Voxel_t outobj = new librav_lcm_msgs.Voxel_t();
        outobj.id = this.id;
 
        outobj.pos_x = this.pos_x;
 
        outobj.pos_y = this.pos_y;
 
        outobj.pos_z = this.pos_z;
 
        outobj.occupied = this.occupied;
 
        return outobj;
    }
 
}

